export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_ITEM_CART = 'REMOVE_ITEM_CART';
export const SAVE_SHIPPING_INFO = 'SAVE_SHIPPING_INFO';

export const FETCH_PROVINCES_REQUEST = 'FETCH_PROVINCES_REQUEST';
export const FETCH_PROVINCES_SUCCESS = 'FETCH_PROVINCES_SUCCESS';
export const FETCH_PROVINCES_FAIL = 'FETCH_PROVINCES_FAIL';

export const FETCH_DISTRICTS_REQUEST = 'FETCH_DISTRICTS_REQUEST';
export const FETCH_DISTRICTS_SUCCESS = 'FETCH_DISTRICTS_SUCCESS';
export const FETCH_DISTRICTS_FAIL = 'FETCH_DISTRICTS_FAIL';

export const FETCH_WARDS_REQUEST = 'FETCH_WARDS_REQUEST';
export const FETCH_WARDS_SUCCESS = 'FETCH_WARDS_SUCCESS';
export const FETCH_WARDS_FAIL = 'FETCH_WARDS_FAIL';

export const CLEAR_DISTRICTS_AND_WARDS = 'CLEAR_DISTRICTS_AND_WARDS';
export const CLEAR_WARDS = 'CLEAR_WARDS';

export const CLEAR_CART = 'CLEAR_CART';

export const CLEAR_ERRORS = 'CLEAR_ERRORS';
